# Generated by Django 5.0.6 on 2026-01-15 06:58

import apps.organization.models
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=256)),
                ("logo", models.CharField(max_length=256)),
                (
                    "slug_name",
                    models.SlugField(
                        max_length=64,
                        unique=True,
                        validators=[apps.organization.models.no_underscore_validator],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "total_spaces",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "rabbitmq_vhost",
                    models.CharField(
                        blank=True,
                        help_text="Assigned RabbitMQ pooled vhost",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "rabbitmq_provisioned_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When RabbitMQ resources were provisioned",
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
