# Generated by Django 5.0.6 on 2026-01-15 06:58

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=256)),
                ("description", models.TextField()),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=256), size=None
                    ),
                ),
                (
                    "permissions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("UPDATE_ORGANIZATION", "Update Organization"),
                                ("DELETE_ORGANIZATION", "Delete Organization"),
                                ("READ_ORGANIZATION_ROLE", "Read Organization Role"),
                                (
                                    "CREATE_ORGANIZATION_ROLE",
                                    "Create Organization Role",
                                ),
                                (
                                    "UPDATE_ORGANIZATION_ROLE",
                                    "Update Organization Role",
                                ),
                                (
                                    "DELETE_ORGANIZATION_ROLE",
                                    "Delete Organization Role",
                                ),
                                (
                                    "READ_ORGANIZATION_MEMBER",
                                    "Read Organization Member",
                                ),
                                (
                                    "INVITE_ORGANIZATION_MEMBER",
                                    "Invite Organization Member",
                                ),
                                (
                                    "UPDATE_ORGANIZATION_MEMBER_ROLE",
                                    "Update Organization Member Role",
                                ),
                                (
                                    "REMOVE_ORGANIZATION_MEMBER",
                                    "Remove Organization Member",
                                ),
                                (
                                    "READ_ORGANIZATION_DEVICE",
                                    "Read Organization Device",
                                ),
                                (
                                    "CREATE_ORGANIZATION_DEVICE",
                                    "Create Organization Device",
                                ),
                                (
                                    "UPDATE_ORGANIZATION_DEVICE",
                                    "Update Organization Device",
                                ),
                                (
                                    "DELETE_ORGANIZATION_DEVICE",
                                    "Delete Organization Device",
                                ),
                            ],
                            max_length=256,
                        ),
                        size=None,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrganizationRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=256)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_role",
                        to="organization.organization",
                    ),
                ),
                (
                    "policies",
                    models.ManyToManyField(to="organization_roles.organizationpolicy"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrganizationRoleUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_role_user",
                        to="organization_roles.organizationrole",
                    ),
                ),
                (
                    "root_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_role_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
