# Generated by Django 5.0.6 on 2026-06-01 02:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organization", "0004_alter_organization_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationSetting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("brand_name", models.CharField(blank=True, max_length=255)),
                ("site_title", models.CharField(blank=True, max_length=255)),
                ("site_description", models.TextField(blank=True)),
                ("border_radius", models.JSONField(blank=True, default=dict)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_settings",
                        to="organization.organization",
                    ),
                ),
            ],
            options={
                "db_table": "organization_settings",
            },
        ),
        migrations.CreateModel(
            name="OrganizationTheme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("theme_key", models.CharField(max_length=50)),
                ("favicon", models.CharField(blank=True, max_length=500)),
                ("logo", models.CharField(blank=True, max_length=500)),
                ("theme_colors", models.JSONField(blank=True, default=dict)),
                (
                    "setting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="themes",
                        to="organization_setting.organizationsetting",
                    ),
                ),
            ],
            options={
                "db_table": "organization_themes",
            },
        ),
        migrations.AddConstraint(
            model_name="organizationtheme",
            constraint=models.UniqueConstraint(
                fields=("setting", "theme_key"),
                name="unique_organization_theme_key_per_setting",
            ),
        ),
    ]
