# Generated by Django 5.0.6 on 2026-05-27 09:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organization", "0004_alter_organization_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("sign_in", "Sign In"),
                            ("sign_up", "Sign Up"),
                            ("forget_password", "Forget Password"),
                            ("change_password", "Change Password"),
                        ],
                        max_length=255,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(blank=True, max_length=255, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("theme_colors", models.JSONField(blank=True, default=dict)),
                (
                    "background_image",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("show_logo", models.BooleanField(default=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_custom_page",
                        to="organization.organization",
                    ),
                ),
            ],
            options={
                "db_table": "custom_pages",
                "ordering": ["-created_at"],
            },
        ),
    ]
