# Generated by Django 5.0.6 on 2026-06-01 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organization", "0004_alter_organization_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationEmail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("invitation_to_space", "Invitation To Space"),
                            ("verification_code", "Verification Code"),
                            ("reset_password", "Reset Password"),
                        ],
                        max_length=255,
                    ),
                ),
                ("sender_name", models.CharField(blank=True, max_length=255)),
                ("sender_email", models.CharField(blank=True, max_length=255)),
                ("theme_colors", models.JSONField(blank=True, default=dict)),
                ("footer_text", models.TextField(blank=True)),
                (
                    "header_image",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("show_logo", models.BooleanField(default=True)),
                ("social_links", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_custom_emails",
                        to="organization.organization",
                    ),
                ),
            ],
            options={
                "db_table": "custom_emails",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "email_type"),
                        name="unique_organization_email_type",
                    )
                ],
            },
        ),
    ]
