# Generated by Django 5.0.6 on 2026-08-06 02:35

import django.db.models.deletion
from django.db import migrations, models


def backfill_organization_setting(apps, schema_editor):
    OrganizationEmail = apps.get_model("custom_email", "OrganizationEmail")
    OrganizationSetting = apps.get_model("organization_setting", "OrganizationSetting")

    organization_setting_map = {
        s.organization_id: s.id
        for s in OrganizationSetting.objects.only("id", "organization_id")
    }

    updates = []

    for email in OrganizationEmail.objects.exclude(organization_id=None).iterator():
        if setting_id := organization_setting_map.get(email.organization_id):
            email.organization_setting_id = setting_id
            updates.append(email)

    if updates:
        OrganizationEmail.objects.bulk_update(
            updates,
            ["organization_setting"],
            batch_size=1000,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("custom_email", "0002_backfill_organization_emails"),
        ("organization_setting", "0002_backfill_organization_settings"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="organizationemail",
            name="unique_organization_email_type",
        ),
        migrations.AddField(
            model_name="organizationemail",
            name="organization_setting",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_setting_custom_emails",
                to="organization_setting.organizationsetting",
            ),
        ),
        migrations.RunPython(
            backfill_organization_setting,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="organizationemail",
            name="organization",
        ),
        migrations.AddConstraint(
            model_name="organizationemail",
            constraint=models.UniqueConstraint(
                fields=("organization_setting", "email_type"),
                name="unique_organization_email_type",
            ),
        ),
    ]
